name: "usb-construct PR Tests"
on:
  pull_request: {}

jobs:
  test-usb-construct:
    name: 'usb_construct PR Tests (Python ${{ matrix.python-version }})'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13.0-rc.2', 'pypy3.10-v7.3.16']
      fail-fast: true

    steps:
      - name: 'Setup Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: 'Initialize Env'
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "$HOME/.local/bin:$PATH" >> $GITHUB_PATH
          echo "GITHUB_WORKSPACE=\"`pwd`\"" >> $GITHUB_ENV

      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup'
        shell: bash
        run: |
          python -m pip install --user --upgrade pip setuptools wheel setuptools_scm nox

      - name: 'Run Tests'
        timeout-minutes: 15 # Python 3.12 and 3.13 seem to just hang on testing ~sometimes~
        continue-on-error: ${{ matrix.python-version == '3.12' || matrix.python-version == '3.13.0-rc.2' }}
        shell: bash
        run: |
          nox -s test

      - name: 'Codecov'
        if: success() && github.repository == 'shrine-maiden-heavy-industries/usb-construct'
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          files: ./build/tests/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
